### ISSUE TITLE
Potentially wrong SDL PIXELFORMAT enum constants

### ISSUE THREAD

**Issue by immortalx74** [thenumbernine/lua-ffi-bindings#3]
Thanks for these awesome bindings!
I'm porting a project of mine where I was previously using [sonoro1234's](https://github.com/sonoro1234/LuaJIT-SDL2) bindings. With your SDL bindings I'm getting an `Unsupported YUV format` error when trying to create a texture with `SDL_CreateTexture`.
That happens with any of the `SDL_PIXELFORMAT_XXXX` enum values. So I replaced the definition of the pixel-format I wanted to use, with that of sonoro1234's and it worked.

It might be something I'm doing wrong on my end but I thought I'd let you know.

**Comment by thenumbernine** [comment]
Thanks, glad to provide.
This project as a whole was a spin-off of malkia's [UFO](https://github.com/malkia/ufo) project.
Since branching off from that, I developed a [lua C pre-processor](https://github.com/thenumbernine/preproc-lua), with luajit-ffi bindings generator.
While all other bindings are generating fine with the preprocessor, unfortunately, the SDL headers are proving too much for it, and as a result I haven't been able to regenerate the SDL bindings for a while ...
... hence why they are dated.

With all that rant aside, while I don't know what SDL version the original binding code came from, it looks like I'm using SDL 2.28.3 
It looks like from whatever version the bindings are until this version, someone changed the pixel format highest bit from bit 31 to bit 28 ...

**Comment by thenumbernine** [comment]
I've fixed the bit, but it looks like still there are a few `SDL_PIXELFORMAT_`'s missing

**Comment by thenumbernine** [comment]
...and I added those new ones too.

**Comment by thenumbernine** [comment]
I have now regenerated the sdl.lua file (and you can too if you want to jump through the hoops in the preproc-lua project)
but in getting it working, now my lua-generated-header-files have spit out too many enums, and luajit is getting table overflows.
This is a known limitation of luajit - that you can only define so many enums before it just craps out.
So I am not yet submitting the latest SDL generated header into this repo yet, but just for reference's sake, know that it can be generated.

**Comment by immortalx74** [comment]
Thanks so much and no worries! I've been using these bindings for about a week and it's been a pleasure to work with!

**Comment by thenumbernine** [comment]
Ok in the latest commit I've regenerated all headers, including SDL, and tried to trim out as many unnecessary enums as possible to get it to still run alright without "table overflow" errors.
